language: cpp

compiler:
  - gcc
  - clang

branches:
  only:
    - master

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libqt4-dev libqt4-private-dev libev4 libev-dev

script:
  - qmake
  - make
  - cd tests-qt4
  - for i in ./tst_*; do ./$i; done
