install:
  - sudo apt-get update
  - sudo apt-get install libqt4-dev libqt4-private-dev

script:
  - cd src
  - qmake
  - make
  - cd ../tests-qt4
  - qmake
  - make
  - for i in ./tst_*; do ./$i; done

notifications:
  email: false
